### ISSUE TITLE
Make nvcodedark it's own executable file, packer location, cache dir, and config dir.

### ISSUE THREAD

**Issue by SingularisArt** [AlphaTechnolog/nvcodark#4]
I really see this project going far into the future, but I'm curious about one thing. Do you think you might be able to create nvcodark's own:
1. Executable file. Maybe something like: `~/.local/bin/nvcodark`
2. Directory. Maybe something like: `~/.local/share/nvcodark/nvcodark`
3. Packer location. Maybe something like: `~/.local/share/nvcodark/site`
4. Cache dir. Maybe something like: `~/.cache/nvcodark`
5. Config dir. Maybe something like: `~/.config/nvcodark`

If you fancy this idea, I'll be willing to implement this.
NOTE: If you haven't noticed yet, I'm replicating how LunarVim and DeathVim maintain their code.

**Comment by AlphaTechnolog** [comment]
ohh, that could be a good idea, i didn't noticed that this can be possible lmao, nvcodark is in a remake process (you can check the dev branch), that's why i think that implement that right now couldn't be good, but i think this could be good for the remake (it's on the dev branch, but without instructions yet), so really ty, and your help will be really really appreciated of course!

**Comment by SingularisArt** [comment]
Yeah. I think it'll be easier to create that setup from now on instead of trying to implement it after we've already created an advanced setup.
I'll see what I can do throughout this week.

**Comment by SingularisArt** [comment]
Edit: I just created the pull request.
